# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pokemon_game_pb2 as pokemon__game__pb2


class PokemonGameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.checkboard = channel.unary_unary(
                '/pokemon_game.PokemonGame/checkboard',
                request_serializer=pokemon__game__pb2.name.SerializeToString,
                response_deserializer=pokemon__game__pb2.checkpos.FromString,
                )
        self.Move = channel.unary_unary(
                '/pokemon_game.PokemonGame/Move',
                request_serializer=pokemon__game__pb2.movepos.SerializeToString,
                response_deserializer=pokemon__game__pb2.movecomplete.FromString,
                )
        self.pokemon_list = channel.unary_unary(
                '/pokemon_game.PokemonGame/pokemon_list',
                request_serializer=pokemon__game__pb2.name.SerializeToString,
                response_deserializer=pokemon__game__pb2.pokemon_captured.FromString,
                )
        self.client_path = channel.unary_unary(
                '/pokemon_game.PokemonGame/client_path',
                request_serializer=pokemon__game__pb2.name.SerializeToString,
                response_deserializer=pokemon__game__pb2.path.FromString,
                )
        self.trainer_list = channel.unary_unary(
                '/pokemon_game.PokemonGame/trainer_list',
                request_serializer=pokemon__game__pb2.name.SerializeToString,
                response_deserializer=pokemon__game__pb2.pokemon_captured.FromString,
                )


class PokemonGameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def checkboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pokemon_list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def client_path(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def trainer_list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PokemonGameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'checkboard': grpc.unary_unary_rpc_method_handler(
                    servicer.checkboard,
                    request_deserializer=pokemon__game__pb2.name.FromString,
                    response_serializer=pokemon__game__pb2.checkpos.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=pokemon__game__pb2.movepos.FromString,
                    response_serializer=pokemon__game__pb2.movecomplete.SerializeToString,
            ),
            'pokemon_list': grpc.unary_unary_rpc_method_handler(
                    servicer.pokemon_list,
                    request_deserializer=pokemon__game__pb2.name.FromString,
                    response_serializer=pokemon__game__pb2.pokemon_captured.SerializeToString,
            ),
            'client_path': grpc.unary_unary_rpc_method_handler(
                    servicer.client_path,
                    request_deserializer=pokemon__game__pb2.name.FromString,
                    response_serializer=pokemon__game__pb2.path.SerializeToString,
            ),
            'trainer_list': grpc.unary_unary_rpc_method_handler(
                    servicer.trainer_list,
                    request_deserializer=pokemon__game__pb2.name.FromString,
                    response_serializer=pokemon__game__pb2.pokemon_captured.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pokemon_game.PokemonGame', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PokemonGame(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def checkboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_game.PokemonGame/checkboard',
            pokemon__game__pb2.name.SerializeToString,
            pokemon__game__pb2.checkpos.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_game.PokemonGame/Move',
            pokemon__game__pb2.movepos.SerializeToString,
            pokemon__game__pb2.movecomplete.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def pokemon_list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_game.PokemonGame/pokemon_list',
            pokemon__game__pb2.name.SerializeToString,
            pokemon__game__pb2.pokemon_captured.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def client_path(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_game.PokemonGame/client_path',
            pokemon__game__pb2.name.SerializeToString,
            pokemon__game__pb2.path.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def trainer_list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_game.PokemonGame/trainer_list',
            pokemon__game__pb2.name.SerializeToString,
            pokemon__game__pb2.pokemon_captured.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
